CREATE OR REPLACE FUNCTION FN_GET_HRMCODE_NAMES(IN_CODETYPE VARCHAR2, IN_STR VARCHAR2)
	RETURN VARCHAR2
IS
	V_CODENAME VARCHAR2(500);
	V_RTN VARCHAR2(4000);
BEGIN 
	
  FOR REC IN (
			  SELECT REGEXP_SUBSTR(IN_STR, '[^,]+', 1, LEVEL) AS CODE
	 		    FROM DUAL
			 CONNECT 
			      BY REGEXP_SUBSTR(IN_STR, '[^,]+', 1, LEVEL) IS NOT NULL
			 )
  LOOP
    BEGIN	  
      SELECT CODE_NM
        INTO V_CODENAME
        FROM HRMCODE A
       WHERE A.TYPE_ID = IN_CODETYPE
         AND A.CODE    = REC.CODE;  		          
    END;		        	
    
  	IF V_RTN IS NULL THEN
      V_RTN := V_CODENAME;
  	ELSE 
	  V_RTN := V_RTN||','||V_CODENAME;
  	END IF;
  
 
  END LOOP;

  RETURN V_RTN;
END;
