CREATE TABLE BIZCODETYPE (
	CREATED_DT			  	DATETIME		  	NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,  	
	TYPE_ID				    VARCHAR(10)	  		NOT NULL	,
	TYPE_NM				    VARCHAR(500)		NOT NULL	,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
	PRT_SEQ			      	INT		       		NULL		,
  	BIZ_TYPE				VARCHAR(10)		  	NULL    	,
  	BIZ_RULE_CMT_1      	VARCHAR(500)	  	NULL    	,
  	BIZ_RULE_CMT_2      	VARCHAR(500)	  	NULL    	,
  	BIZ_RULE_CMT_3      	VARCHAR(500)	  	NULL    	,
  	BIZ_RULE_CMT_4      	VARCHAR(500)	  	NULL    	,
  	BIZ_RULE_CMT_5      	VARCHAR(500)	  	NULL    	,
  	BIZ_RULE_CMT_6      	VARCHAR(500)	  	NULL    	,
  	BIZ_RULE_CMT_7      	VARCHAR(500)	  	NULL    	,
  	BIZ_RULE_CMT_8      	VARCHAR(500)	  	NULL    	,
  	BIZ_RULE_CMT_9      	VARCHAR(500)	  	NULL    	,
  	BIZ_RULE_CMT_10     	VARCHAR(500)	  	NULL    	,
	CMT					    TEXT		 	    NULL 		,
	constraint pk_bizcodetype primary key(TYPE_ID, ORG_CD)
);
COMMENT ON TABLE BIZCODETYPE IS '업무코드구분';

CREATE TABLE BIZCODE (
	CREATED_DT			  	DATETIME		  	NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,  
	TYPE_ID				    VARCHAR(10)	  		NOT NULL	,	
  	CODE	  			    VARCHAR(10)	  		NOT NULL	,  
	CODE_NM				    VARCHAR(500)		NOT NULL	,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
	USE_YN  				BOOLEAN	    	  	NULL    	,
  	PRT_SEQ			      	INT		       		NULL		,    
	CMT					    TEXT		 	    NULL 		,
	ADDITIONAL				TEXT		 	    NULL 		,
	constraint pk_bizcode primary key(TYPE_ID, CODE, ORG_CD)
);
COMMENT ON TABLE BIZCODE IS '업무코드';


CREATE TABLE HRMCODETYPE (
	CREATED_DT			  	DATETIME		  	NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	TYPE_ID				    VARCHAR(10)	  		NOT NULL	,
	TYPE_NM				    VARCHAR(600)		NOT NULL	,
	PRT_SEQ			      	INT		       		NULL		,
	CMT					    TEXT		 	    NULL 		,
	FIELD_CONFIG		    TEXT		 	    NULL 		,
	constraint pk_hrmcodetype primary key(TYPE_ID)
);
COMMENT ON TABLE HRMCODETYPE IS 'HRM코드구분';


CREATE TABLE HRMCODE (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	TYPE_ID					VARCHAR(10)	  		NOT NULL	,
  	CODE  				    VARCHAR(10)	  		NOT NULL	,
	CODE_NM				    VARCHAR(600)		NOT NULL	,
	USE_YN			      	BOOLEAN			  	NOT NULL	,
	PRT_SEQ			      	INT		       		NULL		,
	CMT					    TEXT		 	    NULL 		,
  	EXTRA_INFO				TEXT		 	    NULL 		,
	constraint pk_hrmcode primary key(TYPE_ID, CODE),
 	constraint fk_hrmcode1 	foreign key(TYPE_ID) references HRMCODETYPE(TYPE_ID)
);
COMMENT ON TABLE HRMCODE IS 'HRM코드';

CREATE TABLE HRMSTAFF (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	STAFF_NO			    VARCHAR(10)			NOT NULL	,
  	STAFF_NAME		      	VARCHAR(50)			NULL    	,
  	STAFF_NAME_ENG	    	VARCHAR(50)			NULL    	,
  	STAFF_NAME_CHI	    	VARCHAR(50)			NULL    	,
  	STAFF_YN				BOOLEAN				NULL		,
  	RREGNO	            	VARCHAR(20)			NULL    	,  	
  	GENDER              	VARCHAR(20)			NULL    	,
  	BIRTHDAY            	DATETIME  			NULL    	,
  	IMG_PATH            	VARCHAR(50)			NULL    	,
  	PARTNER_COMP_CODE		VARCHAR(10)			NULL    	,
  	JOIN_COMP_DT			DATETIME  			NULL    	,
  	RETIRE_COMP_DT			DATETIME  			NULL    	,
  	WORK_STATE_CODE     	VARCHAR(20)			NULL    	,  		
  	BLNG_DEPT_CODE      	VARCHAR(10)			NULL    	,	
  	WORK_DEPT_CODE      	VARCHAR(10)			NULL    	,	
  	JOB_GROUP_CODE      	VARCHAR(10)			NULL    	,	
  	JOB_POSITION_CODE   	VARCHAR(10)			NULL    	,	
  	OCCUPATION_CODE     	VARCHAR(10)			NULL    	,	
  	JOB_GRADE_CODE      	VARCHAR(10)			NULL    	,	
  	PAY_STEP_CODE       	VARCHAR(10)			NULL    	,	
  	JOB_CODE            	VARCHAR(10)			NULL    	,	
	constraint pk_hrmstaff primary key(STAFF_NO, ORG_CD)
);
COMMENT ON TABLE HRMSTAFF IS '직원정보';

CREATE TABLE HRMSTAFFCONTACT (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	STAFF_NO			    VARCHAR(10)			NOT NULL	,
  	CONTACT_TYPE	      	VARCHAR(10)			NOT NULL	,  
  	ADDR_TYPE				VARCHAR(10)			NULL    	,	
  	POST_NO					VARCHAR(10)			NULL    	,
  	MAIN_ADDR				VARCHAR(500)		NULL    	,
  	SUB_ADDR				VARCHAR(500)		NULL    	,
  	PHONE_NO				VARCHAR(500)		NULL    	,
	constraint pk_hrmstaffcontact primary key(ORG_CD, STAFF_NO, CONTACT_TYPE)
);
COMMENT ON TABLE HRMSTAFFCONTACT IS '직원연락처정보';

CREATE TABLE HRMSTAFFAPPOINTMENTRECORD (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	STAFF_NO			    VARCHAR(10)			NOT NULL	,
  	SEQ       		      	INT       			NOT NULL	,
  	APPOINTMENT_TYPE_CODE 	VARCHAR(10)	  		NOT NULL	,  
  	APPOINTMENT_DT	    	DATETIME	  		NOT NULL	,
  	APPOINTMENT_END_DT		DATETIME  			NULL    	,
  	RECORD_NAME		      	VARCHAR(50)			NULL    	,  
  	CMT       		      	VARCHAR(2000)		NULL    	,  
  	APPLY_TYPE_CD       	VARCHAR(2)     		NULL    	,
  	COMPLETE_YN       		BOOLEAN	      		NULL    	,  
  	BLNG_DEPT_CODE      	VARCHAR(10)			NULL    	,	
  	WORK_DEPT_CODE      	VARCHAR(10)			NULL    	,	
  	JOB_GROUP_CODE      	VARCHAR(10)			NULL    	,	
  	JOB_POSITION_CODE   	VARCHAR(10)			NULL    	,	
  	OCCUPATION_CODE     	VARCHAR(10)			NULL    	,	
  	JOB_GRADE_CODE      	VARCHAR(10)			NULL    	,	
  	PAY_STEP_CODE       	VARCHAR(10)			NULL    	,	
  	JOB_CODE            	  VARCHAR(10)		NULL    	,	
  	DUTY_RESPONSIBILITY_CODE  VARCHAR(10)		NULL    	,	
	constraint pk_hrmstaffappointmentrecord primary key(ORG_CD, STAFF_NO, SEQ)
);
COMMENT ON TABLE HRMSTAFFAPPOINTMENTRECORD IS '직원발령기록';

CREATE TABLE HRMSTAFFDUTYRESPONSIBILITY (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	STAFF_NO			    VARCHAR(10)			NOT NULL	,
  	SEQ       		      	INT       			NOT NULL	,  
  	DUTY_RESPONSIBILITY_CODE  VARCHAR(10)		NULL    	,	
  	FROM_DT			        DATETIME		    NULL    	,
  	TO_DT 			        DATETIME		    NULL    	,
  	PAY_APPLY_YN 			BOOLEAN 		    NULL    	,
	constraint pk_hrmstaffdutyresponsibility primary key(ORG_CD, STAFF_NO, SEQ)
);
COMMENT ON TABLE HRMSTAFFDUTYRESPONSIBILITY IS '직원직책정보';

CREATE TABLE HRMSTAFFFAMILY (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	STAFF_NO			    VARCHAR(10)			NOT NULL	,
  	SEQ       		      	INT       			NOT NULL	, 	 
  	FAMILY_NAME         	VARCHAR(50)			NULL    	,		
  	RREGNO              	VARCHAR(50)			NULL    	,	
  	FAMILY_REL_CODE     	VARCHAR(50)			NULL    	,	
  	OCCUPATION_NAME     	VARCHAR(50)			NULL    	,	
  	SCHOOL_CAREER_CODE  	VARCHAR(50)			NULL    	,		
  	CMT                 	VARCHAR(2000)	  	NULL    	,	
	constraint pk_hrmstafffamily primary key(ORG_CD, STAFF_NO, SEQ)
);
COMMENT ON TABLE HRMSTAFFFAMILY IS '직원가족정보';

CREATE TABLE HRMSTAFFLICENSE (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	STAFF_NO			    VARCHAR(10)			NOT NULL	,
  	SEQ       		      	INT       			NOT NULL	,  
  	LICENSE_TYPE        	VARCHAR(50)			NULL    	,	
  	LICENSE_NO          	VARCHAR(50)			NULL    	,	
  	DATE_OF_ACQUISITION 	DATETIME  			NULL    	,	
  	CERTIFICATION_AUTHORITY VARCHAR(50)			NULL    	,	  
  	CMT                 	VARCHAR(2000)	  	NULL    	,	
	constraint pk_hrmstafflicense primary key(ORG_CD, STAFF_NO, SEQ)
);
COMMENT ON TABLE HRMSTAFFLICENSE IS '직원가족정보';

CREATE TABLE HRMSTAFFSCHOOLCAREER (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	STAFF_NO			    VARCHAR(10)			NOT NULL	,
  	SEQ       		      	INT       			NOT NULL	,	  
  	SCHOOL_CAREER_CODE  	VARCHAR(50)			NULL    	,	
  	SCHOOL_CODE         	VARCHAR(50)			NULL    	,	
  	FROM_DT             	DATETIME  			NULL    	,	
  	TO_DT               	DATETIME  			NULL    	,	
  	MAJOR_NAME          	VARCHAR(50)			NULL    	,	
  	PLURAL_MAJOR_NAME   	VARCHAR(50)			NULL    	,	
  	LOCATION_NAME       	VARCHAR(50)			NULL    	,		
  	LESSON_YEAR         	VARCHAR(50)			NULL    	,	  
  	CMT                 	VARCHAR(2000)	  	NULL    	,	
	constraint pk_hrmstaffschoolcareer primary key(ORG_CD, STAFF_NO, SEQ)
);
COMMENT ON TABLE HRMSTAFFSCHOOLCAREER IS '직원가족정보';

CREATE TABLE HRMSTAFFPERIOD (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	STAFF_NO			    VARCHAR(10)			NOT NULL	,
  	PERIOD_TYPE_CD			VARCHAR(10)			NOT NULL	,	
  	SEQ       		      	INT       			NOT NULL	,	    	
  	FROM_DT             	DATETIME  			NULL    	,	
  	TO_DT               	DATETIME  			NULL    	,	  		 
  	CMT                 	VARCHAR(2000)	  	NULL    	,	
	constraint pk_hrmstaffperiod primary key(ORG_CD, STAFF_NO, PERIOD_TYPE_CD, SEQ)
);
COMMENT ON TABLE HRMSTAFFPERIOD IS '직원가족정보';

CREATE TABLE HRMDUTYAPP (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	DUTY_ID          	 	BIGINT             	NOT NULL 	,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	STAFF_NO			    VARCHAR(10)			NOT NULL	,  		   	
  	DUTY_REASON         	VARCHAR(50)			NULL    	,	  		  		
  	CMT                 	VARCHAR(2000)	  	NULL    	,	
	constraint pk_hrmdutyapp primary key(DUTY_ID)
);
COMMENT ON TABLE HRMDUTYAPP IS '근태신청';

CREATE TABLE HRMDUTYAPPDETAIL (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	DETAIL_ID          	 	BIGINT             	NOT NULL  	,
	DUTY_ID          	 	BIGINT             	NOT NULL  	,
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	STAFF_NO			    VARCHAR(10)			NOT NULL	,  		 
  	DUTY_CODE 				VARCHAR(50)			NOT NULL   	,	
  	DUTY_REASON         	VARCHAR(50)			NULL    	,	
  	FROM_DT 	          	DATETIME  			NULL    	,	
  	TO_DT   	          	DATETIME  			NULL    	,
  	HHMM					VARCHAR(4)			NULL		,	  		 
  	CMT                 	VARCHAR(2000)	  	NULL    	,	
	constraint pk_hrmdutyappdetail primary key(DETAIL_ID),
	constraint fk_hrmdutyappdetail 	foreign key(DUTY_ID) references HRMDUTYAPP(DUTY_ID)
);
COMMENT ON TABLE HRMDUTYAPPDETAIL IS '근태신청상세';


CREATE TABLE HRMPAYITEM (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,	
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	PAY_ITEM_CODE		    VARCHAR(10)			NOT NULL	,  		   	
  	PAY_ITEM_NAME         	VARCHAR(50)			NULL    	,	  		  		
  	PAY_ITEM_TYPE          	VARCHAR(10)	 	 	NULL    	,	
  	PAY_TABLE_YN          	BOOLEAN		 	 	NULL    	,
  	SEQ 		         	INT			 	 	NULL    	,
  	CMT						VARCHAR(4000)		NULL		,
	constraint pk_hrmpayitem primary key(ORG_CD, PAY_ITEM_CODE)
);
COMMENT ON TABLE HRMPAYITEM IS '급여항목';

CREATE TABLE HRMPAYTABLE (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	PAY_TABLE_ID			BIGINT				NOT NULL	,	
	ORG_CD				    VARCHAR(10)			NOT NULL	,
  	PAY_ITEM_CODE		    VARCHAR(10)			NOT NULL	,  		   	
  	EFFECTIVE_DT			DATETIME			NULL    	,	  		  		
  	PAY_ITEM_TYPE          	VARCHAR(10)	 	 	NULL    	,	
  	OCCUPATION_CODE         VARCHAR(10)	 	 	NULL    	,
  	JOB_GRADE_CODE  	    VARCHAR(10)	 	 	NULL    	,
  	PAY_STEP_CODE  	       	VARCHAR(10)	 	 	NULL    	,
  	WAGE_AMOUNT				NUMERIC				NULL		,
  	ENABLE_YN				BOOLEAN		 	 	NULL    	,
  	CMT						VARCHAR(4000)		NULL		,
	constraint pk_hrmpaytable primary key(PAY_TABLE_ID)
);
COMMENT ON TABLE HRMPAYTABLE IS '급여테이블';

CREATE TABLE HRMPAYEXPRESSION (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	PAY_EXPR_ID				BIGINT				NOT NULL	,	
	ORG_CD				    VARCHAR(10)			NOT NULL	,
	PAY_ITEM_CODE		    VARCHAR(10)			NOT NULL	,
  	PAY_CONDITION		    VARCHAR(4000)		NULL      	,  		   	  		  		  	  	
  	FORMULA		            VARCHAR(4000)	 	NULL    	,
  	SEQ 		         	INT			 	 	NULL    	,  	
  	CMT						VARCHAR(4000)		NULL		,
	constraint pk_hrmpayexpression primary key(PAY_EXPR_ID)
);
COMMENT ON TABLE HRMPAYEXPRESSION IS '급여조건별계산식';

CREATE TABLE HRMPAYITEMSTAFF (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	PAY_ITEM_STAFF_ID		BIGINT				NOT NULL	,	
	ORG_CD				    VARCHAR(10)			NOT NULL	,
	STAFF_NO			    VARCHAR(10)			NOT NULL	,
  	PAY_ITEM_CODE		    VARCHAR(10)			NOT NULL	,  		   	
  	EFFECTIVE_DT			DATETIME			NULL    	,	  		  		
  	PAY_ITEM_TYPE          	VARCHAR(10)	 	 	NULL    	,	
  	FROM_DT 	          	DATETIME  			NULL    	,	
  	TO_DT   	          	DATETIME  			NULL    	,
  	WAGE_AMOUNT				NUMERIC				NULL		,  	
  	CMT						VARCHAR(4000)		NULL		,
	constraint pk_hrmpayitemstaff primary key(PAY_ITEM_STAFF_ID)
);
COMMENT ON TABLE HRMPAYITEMSTAFF IS '급여항목직원';


CREATE TABLE HRMPAYSTAFF (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	PAY_STAFF_ID		    VARCHAR(50)			NOT NULL	,	
	ORG_CD				    VARCHAR(10)			NOT NULL	,
	PAY_YYYYMM				VARCHAR(6)			NOT NULL	,
	PAY_SEQ					INT					NOT NULL	,
	STAFF_NO			    VARCHAR(10)			NOT NULL	,
	CLOSE_YN				BOOLEAN				NULL		,  	    	  
  	BLNG_DEPT_CODE			VARCHAR(10)			NULL		,
  	WORK_DEPT_CODE			VARCHAR(10)			NULL		,
  	JOB_GROUP_CODE			VARCHAR(10)			NULL		,
  	JOB_POSITION_CODE		VARCHAR(10)			NULL		,
  	OCCUPATION_CODE			VARCHAR(10)			NULL		,
  	JOB_GRADE_CODE			VARCHAR(10)			NULL		,
  	PAY_STEP_CODE			VARCHAR(10)			NULL		,
  	JOB_CODE				VARCHAR(10)			NULL		,
  	DUTY_RESPONSIBILITY_CODE	VARCHAR(10)		NULL		,
	constraint pk_hrmpaystaff primary key(PAY_STAFF_ID)
);
COMMENT ON TABLE HRMPAYSTAFF IS '급여직원';

CREATE TABLE HRMPAYSTAFFITEM (
	CREATED_DT			  	DATETIME			NULL		,
	CREATED_USER_ID			VARCHAR(50)			NULL		,
	CREATED_HOST_IP			VARCHAR(50)			NULL		,
	CREATED_APP_URL			VARCHAR(500)		NULL		,
	MODIFIED_DT			  	DATETIME			NULL		,
	MODIFIED_USER_ID		VARCHAR(50)			NULL		,
	MODIFIED_HOST_IP		VARCHAR(50)			NULL		,
	MODIFIED_APP_URL		VARCHAR(500)		NULL		,
	PAY_STAFF_ITEM_ID	    VARCHAR(50)			NOT NULL	,
	PAY_STAFF_ID		    VARCHAR(50)			NOT NULL	,	
	PAY_ITEM_CODE		    VARCHAR(10)			NOT NULL	,
  	WAGE_AMOUNT				NUMERIC				NULL		,
	constraint pk_hrmpaystaffitem primary key(PAY_STAFF_ITEM_ID),
	constraint fk_hrmpaystaffitem foreign key(PAY_STAFF_ID) references HRMPAYSTAFF(PAY_STAFF_ID)
);
COMMENT ON TABLE HRMPAYSTAFFITEM IS '직원급여항목';
