CREATE TABLE GRWBOARD (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
  	BOARD_ID            	INTEGER         NOT NULL  	,
  	BOARD_P_ID          	INTEGER         NULL    	,
  	BOARD_TYPE          	VARCHAR2(10)    NOT NULL	,
  	BOARD_NAME          	VARCHAR2(500)	NULL    	,
  	BOARD_DESC          	VARCHAR2(4000)	NULL    	,
  	USE_YN              	BOOLEAN         NULL    	,
  	SEQ                 	INTEGER         NULL    	,
  	constraint pk_grwboard primary key(BOARD_ID)
);
COMMENT ON TABLE GRWBOARD IS '게시판';


CREATE TABLE GRWPOST (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
  	POST_ID          		INTEGER         NOT NULL    ,
  	POST_P_ID        		INTEGER         NULL    	,
  	BOARD_ID            	INTEGER         NOT NULL	,
  	USER_ID             	VARCHAR2(500)   NOT NULL	,
  	TITLE               	VARCHAR2(500)	NULL    	,
  	CONTENTS            	CLOB			NULL    	,  	
  	PWD                 	VARCHAR2(500)	NULL    	,
  	DEPTH_LEVEL          	INTEGER         NULL    	,
  	HIT_CNT             	INTEGER         NULL    	,  	
  	TOP_FIXED_YN        	BOOLEAN         NULL    	,  	
  	constraint pk_grwpost primary key(POST_ID),  
  	constraint fk_grwpost1 	foreign key(BOARD_ID) references GRWBOARD(BOARD_ID)
);
COMMENT ON TABLE GRWPOST IS '게시글';

CREATE TABLE GRWPOSTFILE (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
  	POST_FILE_ID     		INTEGER         NOT NULL  	,
  	POST_ID          		INTEGER         NOT NULL	,  
  	FILE_ID             	INTEGER		    NULL		,
  	FILE_PATH				VARCHAR2(500)	NULL		,
  	UUID					VARCHAR2(500)	NULL		,
  	FILE_NM					VARCHAR2(500)	NULL		,
  	FILE_SIZE				INTEGER			NULL		,
  	CONTENT_TYPE			VARCHAR2(500)	NULL		,	  
  	constraint pk_grwpostfile primary key(POST_FILE_ID),  
  	constraint fk_grwpostfile1 foreign key(POST_ID) references GRWPOST(POST_ID)
);
COMMENT ON TABLE GRWPOSTFILE IS '게시글첨부파일';


CREATE TABLE GRWPOSTCHECK (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,  
  	POST_ID  	        	INTEGER         NOT NULL	,
  	USER_ID             	VARCHAR2(50)    NOT NULL	,
  	HIT_CNT             	INTEGER         NULL		,  
  	constraint pk_grwarticlecheck primary key(POST_ID, USER_ID),
  	constraint fk_grwarticlecheck1 foreign key(POST_ID) references GRWPOST(POST_ID)
);
COMMENT ON TABLE GRWPOSTCHECK IS '게시글사용자조회수';


CREATE TABLE GRWWORKCALENDAR(
  	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
  	ID                  	INTEGER         NOT NULL 	,
  	CALENDAR_NAME       	VARCHAR2(500)   NOT NULL	,
  	COLOR               	VARCHAR2(10)    NULL    	,
  	constraint pk_grwworkcalendar primary key(ID)
);
COMMENT ON TABLE GRWWORKCALENDAR IS 'WORKCALENDAR';


CREATE TABLE GRWWORKCALENDAREVENT(
  	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
  	ID                  	INTEGER         NOT NULL 	,
  	FK_WORKCALENDAR     	INTEGER         NOT NULL	,
  	TITLE               	VARCHAR2(500)   NOT NULL	,
  	START_DT            	DATE        	NULL    	,
  	END_DT              	DATE        	NULL    	,
  	ALLDAY              	BOOLEAN         NULL    	,
  	constraint pk_grwworkcalendarevent primary key(ID),
  	constraint fk_grwworkcalendarevent1 foreign key(FK_WORKCALENDAR) references GRWWORKCALENDAR(ID)
);
COMMENT ON TABLE GRWWORKCALENDAREVENT IS 'GRWWORKCALENDAREVENT';

CREATE TABLE GRWWORKCALENDARUSER(
  	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
  	ID                  	INTEGER         NOT NULL ,  
  	USER_ID             	VARCHAR2(500)   NOT NULL	,
  	constraint pk_grwworkcalendaruser primary key(ID, USER_ID),
  	constraint fk_grwworkcalendaruser1 foreign key(ID) references GRWWORKCALENDAR(ID)
);
COMMENT ON TABLE GRWWORKCALENDARUSER IS 'GRWWORKCALENDARUSER';

CREATE TABLE GRWTODOGROUP(
  	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
  	ID                  	INTEGER         NOT NULL 	,
  	TODO_GROUP_NAME     	VARCHAR2(500)   NOT NULL	,
  	USER_ID             	VARCHAR2(500)   NOT NULL	,    
  	constraint pk_grwtodogroup primary key(ID)
);
COMMENT ON TABLE GRWTODOGROUP IS 'TODO그룹';


CREATE TABLE GRWTODO(
  	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
  	ID                  	INTEGER         NOT NULL 	,
  	TODO_GROUP_ID       	INTEGER         NOT NULL	,
  	TODO                	VARCHAR2(500)   NOT NULL	,
  	COMPLETE_YN         	BOOLEAN         NULL    	,
  	DUE_DT              	DATE        	NULL    	,
  	COMMENTS            	VARCHAR2(500)   NULL    	,
  	constraint pk_grwtodo primary key(ID),
  	constraint fk_grwtodo1 foreign key(TODO_GROUP_ID) references GRWTODOGROUP(ID)
);
COMMENT ON TABLE GRWTODO IS 'TODO';

CREATE TABLE GRWTEAM(
  	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
  	TEAM_ID             	INTEGER         NOT NULL ,  
  	TEAM_NAME           	VARCHAR2(500)   NOT NULL	,  
  	constraint pk_grwteam primary key(TEAM_ID)
);
COMMENT ON TABLE GRWTEAM IS 'TEAM';

CREATE TABLE GRWTEAMUSER(
  	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
  	TEAM_ID             	INTEGER         NOT NULL	,  
  	USER_ID             	VARCHAR2(500)   NOT NULL	, 
  	AUTHORITY           	VARCHAR2(500)   NULL    	, 
  	constraint pk_grwteamuser primary key(TEAM_ID, USER_ID),
  	constraint fk_grwteamuser1 foreign key(TEAM_ID) references GRWTEAM(TEAM_ID)
);
COMMENT ON TABLE GRWTEAMUSER IS 'TEAMUSER';
