CREATE TABLE BIZCODETYPE (
	CREATED_DT			  	DATE		  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,  	
	TYPE_ID				    VARCHAR2(10)	NOT NULL	,
	TYPE_NM				    VARCHAR2(500)	NOT NULL	,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
	PRT_SEQ			      	INTEGER		    NULL		,
  	BIZ_TYPE				VARCHAR2(10)	NULL    	,
  	BIZ_RULE_CMT_1      	VARCHAR2(500)	NULL    	,
  	BIZ_RULE_CMT_2      	VARCHAR2(500)	NULL    	,
  	BIZ_RULE_CMT_3      	VARCHAR2(500)	NULL    	,
  	BIZ_RULE_CMT_4      	VARCHAR2(500)	NULL    	,
  	BIZ_RULE_CMT_5      	VARCHAR2(500)	NULL    	,
  	BIZ_RULE_CMT_6      	VARCHAR2(500)	NULL    	,
  	BIZ_RULE_CMT_7      	VARCHAR2(500)	NULL    	,
  	BIZ_RULE_CMT_8      	VARCHAR2(500)	NULL    	,
  	BIZ_RULE_CMT_9      	VARCHAR2(500)	NULL    	,
  	BIZ_RULE_CMT_10     	VARCHAR2(500)	NULL    	,
	CMT					    VARCHAR2(4000)	NULL 		,
	constraint pk_bizcodetype primary key(TYPE_ID, ORG_CD)
);
COMMENT ON TABLE BIZCODETYPE IS '업무코드구분';

CREATE TABLE BIZCODE (
	CREATED_DT			  	DATE		  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,  
	TYPE_ID				    VARCHAR2(10)	NOT NULL	,	
  	CODE	  			    VARCHAR2(10)	NOT NULL	,  
	CODE_NM				    VARCHAR2(500)	NOT NULL	,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
	USE_YN  				BOOLEAN	    	NULL    	,
  	PRT_SEQ			      	INTEGER		    NULL		,    
	CMT					    VARCHAR2(4000)	NULL 		,
	ADDITIONAL				VARCHAR2(4000)	NULL 		,
	constraint pk_bizcode primary key(TYPE_ID, CODE, ORG_CD)
);
COMMENT ON TABLE BIZCODE IS '업무코드';


CREATE TABLE HRMCODETYPE (
	CREATED_DT			  	DATE		  	NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	TYPE_ID				    VARCHAR2(10)	NOT NULL	,
	TYPE_NM				    VARCHAR2(600)	NOT NULL	,
	PRT_SEQ			      	INTEGER		    NULL		,
	CMT					    VARCHAR2(4000)	NULL 		,
	FIELD_CONFIG		    VARCHAR2(4000)	NULL 		,
	constraint pk_hrmcodetype primary key(TYPE_ID)
);
COMMENT ON TABLE HRMCODETYPE IS 'HRM코드구분';


CREATE TABLE HRMCODE (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	TYPE_ID					VARCHAR2(10)	NOT NULL	,
  	CODE  				    VARCHAR2(10)	NOT NULL	,
	CODE_NM				    VARCHAR2(600)	NOT NULL	,
	USE_YN			      	BOOLEAN			NOT NULL	,
	PRT_SEQ			      	INTEGER		    NULL		,
	CMT					    VARCHAR2(4000)	NULL 		,
  	EXTRA_INFO				VARCHAR2(4000)	NULL 		,
	constraint pk_hrmcode primary key(TYPE_ID, CODE),
 	constraint fk_hrmcode1 	foreign key(TYPE_ID) references HRMCODETYPE(TYPE_ID)
);
COMMENT ON TABLE HRMCODE IS 'HRM코드';

CREATE TABLE HRMSTAFF (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
  	STAFF_NO			    VARCHAR2(10)	NOT NULL	,
  	STAFF_NAME		      	VARCHAR2(50)	NULL    	,
  	STAFF_NAME_ENG	    	VARCHAR2(50)	NULL    	,
  	STAFF_NAME_CHI	    	VARCHAR2(50)	NULL    	,
  	STAFF_YN				BOOLEAN			NULL		,
  	RREGNO	            	VARCHAR2(20)	NULL    	,  	
  	GENDER              	VARCHAR2(20)	NULL    	,
  	BIRTHDAY            	DATE  			NULL    	,
  	IMG_PATH            	VARCHAR2(50)	NULL    	,
  	PARTNER_COMP_CODE		VARCHAR2(10)	NULL    	,
  	JOIN_COMP_DT			DATE  			NULL    	,
  	RETIRE_COMP_DT			DATE  			NULL    	,
  	WORK_STATE_CODE     	VARCHAR2(20)	NULL    	,  		
  	BLNG_DEPT_CODE      	VARCHAR2(10)	NULL    	,	
  	WORK_DEPT_CODE      	VARCHAR2(10)	NULL    	,	
  	JOB_GROUP_CODE      	VARCHAR2(10)	NULL    	,	
  	JOB_POSITION_CODE   	VARCHAR2(10)	NULL    	,	
  	OCCUPATION_CODE     	VARCHAR2(10)	NULL    	,	
  	JOB_GRADE_CODE      	VARCHAR2(10)	NULL    	,	
  	PAY_STEP_CODE       	VARCHAR2(10)	NULL    	,	
  	JOB_CODE            	VARCHAR2(10)	NULL    	,	
	constraint pk_hrmstaff primary key(STAFF_NO, ORG_CD)
);
COMMENT ON TABLE HRMSTAFF IS '직원정보';

CREATE TABLE HRMSTAFFCONTACT (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
  	STAFF_NO			    VARCHAR2(10)	NOT NULL	,
  	CONTACT_TYPE	      	VARCHAR2(10)	NOT NULL	,  
  	ADDR_TYPE				VARCHAR2(10)	NULL    	,	
  	POST_NO					VARCHAR2(10)	NULL    	,
  	MAIN_ADDR				VARCHAR2(500)	NULL    	,
  	SUB_ADDR				VARCHAR2(500)	NULL    	,
  	PHONE_NO				VARCHAR2(500)	NULL    	,
	constraint pk_hrmstaffcontact primary key(ORG_CD, STAFF_NO, CONTACT_TYPE)
);
COMMENT ON TABLE HRMSTAFFCONTACT IS '직원연락처정보';

CREATE TABLE HRMSTAFFAPPOINTMENTRECORD (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
  	STAFF_NO			    VARCHAR2(10)	NOT NULL	,
  	SEQ       		      	INTEGER       	NOT NULL	,
  	APPOINTMENT_TYPE_CODE 	VARCHAR2(10)	NOT NULL	,  
  	APPOINTMENT_DT	    	DATE	  		NOT NULL	,
  	APPOINTMENT_END_DT		DATE  			NULL    	,
  	RECORD_NAME		      	VARCHAR2(50)	NULL    	,  
  	CMT       		      	VARCHAR2(2000)	NULL    	,  
  	APPLY_TYPE_CD       	VARCHAR2(2)     NULL    	,
  	COMPLETE_YN       		BOOLEAN	      	NULL    	,  
  	BLNG_DEPT_CODE      	VARCHAR2(10)	NULL    	,	
  	WORK_DEPT_CODE      	VARCHAR2(10)	NULL    	,	
  	JOB_GROUP_CODE      	VARCHAR2(10)	NULL    	,	
  	JOB_POSITION_CODE   	VARCHAR2(10)	NULL    	,	
  	OCCUPATION_CODE     	VARCHAR2(10)	NULL    	,	
  	JOB_GRADE_CODE      	VARCHAR2(10)	NULL    	,	
  	PAY_STEP_CODE       	VARCHAR2(10)	NULL    	,	
  	JOB_CODE            	  VARCHAR2(10)	NULL    	,	
  	DUTY_RESPONSIBILITY_CODE  VARCHAR2(10)	NULL    	,	
	constraint pk_hrmstaffappointmentrecord primary key(ORG_CD, STAFF_NO, SEQ)
);
COMMENT ON TABLE HRMSTAFFAPPOINTMENTRECORD IS '직원발령기록';

CREATE TABLE HRMSTAFFDUTYRESPONSIBILITY (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
  	STAFF_NO			    VARCHAR2(10)	NOT NULL	,
  	SEQ       		      	INTEGER       	NOT NULL	,  
  	DUTY_RESPONSIBILITY_CODE  VARCHAR2(10)	NULL    	,	
  	FROM_DT			        DATE		    NULL    	,
  	TO_DT 			        DATE		    NULL    	,
  	PAY_APPLY_YN 			BOOLEAN 		NULL    	,
	constraint pk_hrmstaffdutyresponsibility primary key(ORG_CD, STAFF_NO, SEQ)
);
COMMENT ON TABLE HRMSTAFFDUTYRESPONSIBILITY IS '직원직책정보';

CREATE TABLE HRMSTAFFFAMILY (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
  	STAFF_NO			    VARCHAR2(10)	NOT NULL	,
  	SEQ       		      	INTEGER       	NOT NULL	, 	 
  	FAMILY_NAME         	VARCHAR2(50)	NULL    	,		
  	RREGNO              	VARCHAR2(50)	NULL    	,	
  	FAMILY_REL_CODE     	VARCHAR2(50)	NULL    	,	
  	OCCUPATION_NAME     	VARCHAR2(50)	NULL    	,	
  	SCHOOL_CAREER_CODE  	VARCHAR2(50)	NULL    	,		
  	CMT                 	VARCHAR2(2000)	NULL    	,	
	constraint pk_hrmstafffamily primary key(ORG_CD, STAFF_NO, SEQ)
);
COMMENT ON TABLE HRMSTAFFFAMILY IS '직원가족정보';

CREATE TABLE HRMSTAFFLICENSE (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
  	STAFF_NO			    VARCHAR2(10)	NOT NULL	,
  	SEQ       		      	INTEGER       	NOT NULL	,  
  	LICENSE_TYPE        	VARCHAR2(50)	NULL    	,	
  	LICENSE_NO          	VARCHAR2(50)	NULL    	,	
  	DATE_OF_ACQUISITION 	DATE  			NULL    	,	
  	CERTIFICATION_AUTHORITY VARCHAR2(50)	NULL    	,	  
  	CMT                 	VARCHAR2(2000)	NULL    	,	
	constraint pk_hrmstafflicense primary key(ORG_CD, STAFF_NO, SEQ)
);
COMMENT ON TABLE HRMSTAFFLICENSE IS '직원가족정보';

CREATE TABLE HRMSTAFFSCHOOLCAREER (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
  	STAFF_NO			    VARCHAR2(10)	NOT NULL	,
  	SEQ       		      	INTEGER       	NOT NULL	,	  
  	SCHOOL_CAREER_CODE  	VARCHAR2(50)	NULL    	,	
  	SCHOOL_CODE         	VARCHAR2(50)	NULL    	,	
  	FROM_DT             	DATE  			NULL    	,	
  	TO_DT               	DATE  			NULL    	,	
  	MAJOR_NAME          	VARCHAR2(50)	NULL    	,	
  	PLURAL_MAJOR_NAME   	VARCHAR2(50)	NULL    	,	
  	LOCATION_NAME       	VARCHAR2(50)	NULL    	,		
  	LESSON_YEAR         	VARCHAR2(50)	NULL    	,	  
  	CMT                 	VARCHAR2(2000)	NULL    	,	
	constraint pk_hrmstaffschoolcareer primary key(ORG_CD, STAFF_NO, SEQ)
);
COMMENT ON TABLE HRMSTAFFSCHOOLCAREER IS '직원가족정보';

CREATE TABLE HRMSTAFFPERIOD (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
  	STAFF_NO			    VARCHAR2(10)	NOT NULL	,
  	PERIOD_TYPE_CD			VARCHAR2(10)	NOT NULL	,	
  	SEQ       		      	INTEGER       	NOT NULL	,	    	
  	FROM_DT             	DATE  			NULL    	,	
  	TO_DT               	DATE  			NULL    	,	  		 
  	CMT                 	VARCHAR2(2000)	NULL    	,	
	constraint pk_hrmstaffperiod primary key(ORG_CD, STAFF_NO, PERIOD_TYPE_CD, SEQ)
);
COMMENT ON TABLE HRMSTAFFPERIOD IS '직원가족정보';

CREATE TABLE HRMDUTYAPP (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	DUTY_ID          	 	INTEGER         NOT NULL 	,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
  	STAFF_NO			    VARCHAR2(10)	NOT NULL	,  		   	
  	DUTY_REASON         	VARCHAR2(50)	NULL    	,	  		  		
  	CMT                 	VARCHAR2(2000)	NULL    	,	
	constraint pk_hrmdutyapp primary key(DUTY_ID)
);
COMMENT ON TABLE HRMDUTYAPP IS '근태신청';

CREATE TABLE HRMDUTYAPPDETAIL (
	CREATED_DT			  	DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT			  	DATE			NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,
	DETAIL_ID          	 	INTEGER         NOT NULL  	,
	DUTY_ID          	 	INTEGER         NOT NULL  	,
	ORG_CD				    VARCHAR2(10)	NOT NULL	,
  	STAFF_NO			    VARCHAR2(10)	NOT NULL	,  		 
  	DUTY_CODE 				VARCHAR2(50)	NOT NULL   	,	
  	DUTY_REASON         	VARCHAR2(50)	NULL    	,	
  	FROM_DT 	          	DATE  			NULL    	,	
  	TO_DT   	          	DATE  			NULL    	,
  	HHMM					VARCHAR2(4)		NULL		,	  		 
  	CMT                 	VARCHAR2(2000)	NULL    	,	
	constraint pk_hrmdutyappdetail primary key(DETAIL_ID),
	constraint fk_hrmdutyappdetail 	foreign key(DUTY_ID) references HRMDUTYAPP(DUTY_ID)
);
COMMENT ON TABLE HRMDUTYAPPDETAIL IS '근태신청상세';



